name: Staging Deployment Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging  # This MUST match the environment name in GitHub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (optional example)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install || echo "No dependencies"

      - name: Run Test (simulation)
        run: echo "Running tests..."

      - name: Simulate Deployment
        run: echo "🚀 Deploying to staging environment..."

