name: V4

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building..."

      - name: Deploy step
        run: echo "Deploying to Production"

