name: CI/CD with Environment

on:
  push:
    branches:
      - main

jobs:
  pre-deploy:
    name: Pre-deployment Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "✅ Running tests..."

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: pre-deploy
    environment:
      name: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Step
        run: echo "🚀 Deploying to Staging environment"

