<<<<<<< HEAD
name: Staging Deployment Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging  # This MUST match the environment name in GitHub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (optional example)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install || echo "No dependencies"

      - name: Run Test (simulation)
        run: echo "Running tests..."

      - name: Simulate Deployment
        run: echo "🚀 Deploying to staging environment..."

=======
name: Azure Login Test

on:
  workflow_dispatch:

jobs:
  login-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure CLI version (to verify login)
        run: az --version
>>>>>>> 0e8365289987eff2bc7dea378896eb46afb3694d
