name: Build with Branch and Path Filters

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'src/**'
      - 'README.md'
    # Optional: exclude some paths
    # paths-ignore:
    #   - 'docs/**'
    #   - 'tests/**'

  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'src/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display branch name
        run: echo "Running on branch: ${{ github.ref_name }}"

      - name: Example build step
        run: echo "Build executed!"

